### ISSUE TITLE
Trying to contact someone from Reign Studios

### ISSUE THREAD

**Issue by Nikolay1243** [zezba9000/UnityMathReference#1]
Hi, 

Sorry to leave this on your project page but I need to talk with someone who worked on the unity plugin! 
Today I went to your website and it's down! Why is this? Anyway, I'm having a problem authenticating with google play and could use your help

My email is nikolay1243@gmail.com.

Cheers

**Comment by zezba9000** [comment]
The server has moved to a different hosting provider. I would post on the "Reign-Unity-Plugin" or "Reign-Unity-Plugin5" issues instead of this one. I don't really have much time for support anymore. Ask the question there and I might know the answer.
